Add the option to pass in a custom port
sgeisler/cargo-remote pull request #13
Opened 2020-05-27 06:04 UTC by lsaether

We run ssh on a custom port so we needed a way to tell cargo remote to use that port instead. I don't usually write Rust so I don't know if this is the most ergonomic solution. Opening mostly for awareness.

2020-05-27 09:14 UTC, sgeisler commented
Will have a closer look at it later and probably merge. But wouldn't it be easier to write a ssh config entry for the build host?

2020-05-28 18:07 UTC, sgeisler requested changes
It would be nice if you could change the "if None, then empty string" statements to a more idiomatic `.args(port.map(|p| format!("-p {}", p)))`.

2020-05-28 18:07 UTC, sgeisler commented on src/main.rs
> +        port: Option<String>,
This should be `Option<u16>`, a `String` allows too many invalid inputs. This would also make `port` `Copy`, avoiding al these `clone()`s.

2021-03-27 10:38 UTC, TheAlgorythm commented
Wouldn't it be better if the port is stored in the config?
Would you accept a PR where I deserialize the config with [serde](https://serde.rs)?

2021-03-27 10:47 UTC, sgeisler commented
@TheAlgorythm tbh I had totally forgotten there was a config file. You are right that that is probably the better place for it. I'm still not sure why you wouldn't just define a host in your ssh config though as cargo remote will probably never support all ssh options.

> Would you accept a PR where I deserialize the config with serde?

Yes, definitely, I'm not sure why I didn't do it this way back then tbh.

2026-05-18 13:06 UTC, lsaether commented
Closing this stale PR since I’m unlikely to refresh it against current main. Thanks for the review and feedback here — if I revisit custom-port support, I’d open a fresh PR around the current code/config shape.

2026-05-18 13:06 UTC, closed without merging